Write basic build configuration script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,27 +1,71 @@
-#!/bin/sh
+#!/bin/bash
 
-# TODO: Check if pthread is found in the searchpaths
-# TODO: Check if zlib is found in the searchpaths
-# TODO: Set correct defines in src/config.h
+# Very basic build configuration script
+# but it does the job at least for now.
+# Requires ldconfig for library checks.
 
-INFILE="src/config.h.in"
+SRC="etc/config.h.in"
+DST="src/config.h"
 
-use_debug="no"
-use_pthread="no"
-use_zlib="no"
+main()
+{
+	local use_debug="no"
+	local use_pthread="no"
+	local use_zlib="no"
 
-if test ! -f "$INFILE"; then
-	echo "Error: Header '$INFILE' missing."
+	# Make sure the config header source file exists
+	test -f "${SRC}" || error "Header '${SRC}' missing."
+
+	# Prompt user to enable debug mode
+	prompt "Enable debug mode?" && use_debug="yes"
+
+	# Check linker searchpaths for libraries
+	exists "libpthread" && use_pthread="yes"
+	exists "libz"       && use_zlib="yes"
+
+	printf "Checking for debug...${use_debug}\n"
+	printf "Checking for pthread...${use_pthread}\n"
+	printf "Checking for zlib...${use_zlib}\n"
+
+	# Process input file
+	cp "${SRC}" "${DST}"
+
+	define "DEBUG"         "${use_debug}"
+	define "HAVE_PTHREAD"  "${use_pthread}"
+	define "HAVE_ZLIB"     "${use_zlib}"
+
+	printf "Configuration finished.\n"
+
+	return 0
+}
+
+exists()
+{
+	ldconfig -p | grep "${1}\.so" >/dev/null
+	return ${?}
+}
+
+define()
+{
+	case "${2}" in
+	yes) sed -i "s/undef ${1}/define ${1}/g" "${DST}" ;;
+	*)   sed -i "s/define ${1}/undef ${1}/g" "${DST}" ;;
+	esac
+}
+
+prompt()
+{
+	read -p "${1} [y/N] " ch
+	case "${ch}" in
+	y|Y) return 0 ;;
+	*)   return 1 ;;
+	esac
+}
+
+error()
+{
+	printf "Error: ${1}\n"
 	exit 1
-fi
+}
 
-read -p "Enable debug mode? [y/N] " debug
-case "$debug" in
-y|Y) use_debug="yes" ;;
-*)   use_debug="no"  ;;
-esac
-
-echo "Checking for debug...$use_debug"
-echo "Checking for pthread...$use_pthread"
-echo "Checking for zlib...$use_zlib"
-echo "Configuration finished."
+main $@
